"""empty message

Revision ID: 1b12e7651d2a
Revises: 6282cd5d9600
Create Date: 2022-01-06 21:26:39.916828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b12e7651d2a'
down_revision = '6282cd5d9600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'added_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('added_by', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
