"""empty message

Revision ID: 2f759f1e37fa
Revises: e65c6aa323ac
Create Date: 2022-01-02 11:18:28.005673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f759f1e37fa'
down_revision = 'e65c6aa323ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('purchased', sa.DateTime(), nullable=True))
    op.add_column('asset', sa.Column('owner', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_asset_owner'), 'asset', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_owner'), table_name='asset')
    op.drop_column('asset', 'owner')
    op.drop_column('asset', 'purchased')
    # ### end Alembic commands ###
