"""empty message

Revision ID: 41d0e83ecda7
Revises: 0a65ab8661c4
Create Date: 2022-01-06 21:24:48.256648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d0e83ecda7'
down_revision = '0a65ab8661c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'asset', 'user', ['added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset', type_='foreignkey')
    # ### end Alembic commands ###
