"""empty message

Revision ID: 76672813f985
Revises: 9474aeb50a2c
Create Date: 2022-01-06 11:09:44.395932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76672813f985'
down_revision = '9474aeb50a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'asset', 'user', ['added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset', type_='foreignkey')
    # ### end Alembic commands ###
