"""empty message

Revision ID: d2086dbb4522
Revises: 2f759f1e37fa
Create Date: 2022-01-02 11:21:19.601443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2086dbb4522'
down_revision = '2f759f1e37fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('serial_number', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_asset_serial_number'), 'asset', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_serial_number'), table_name='asset')
    op.drop_column('asset', 'serial_number')
    # ### end Alembic commands ###
