"""empty message

Revision ID: e65c6aa323ac
Revises: 55d41c56bda6
Create Date: 2022-01-02 11:14:51.768110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65c6aa323ac'
down_revision = '55d41c56bda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('purchased', sa.DateTime(), nullable=False))
    op.add_column('asset', sa.Column('owner', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_asset_owner'), 'asset', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_owner'), table_name='asset')
    op.drop_column('asset', 'owner')
    op.drop_column('asset', 'purchased')
    # ### end Alembic commands ###
